# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CodeProjects\MatrixSolver\python-edition\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1127, 802)
        main_window.setStyleSheet("background: rgb(7, 11, 20);\n"
"")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_bar_widget.sizePolicy().hasHeightForWidth())
        self.top_bar_widget.setSizePolicy(sizePolicy)
        self.top_bar_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.top_bar_widget.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(20, 49, 83, 255), stop:1 rgba(22, 29, 55, 255));\n"
"border-radius: 15px;\n"
"")
        self.top_bar_widget.setObjectName("top_bar_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar_widget)
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_for_back_main_page = QtWidgets.QPushButton(self.top_bar_widget)
        self.btn_for_back_main_page.setMinimumSize(QtCore.QSize(90, 0))
        font = QtGui.QFont()
        font.setFamily("Plus Jakarta Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_for_back_main_page.setFont(font)
        self.btn_for_back_main_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_for_back_main_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_for_back_main_page.setStyleSheet("background: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\CodeProjects\\MatrixSolver\\python-edition\\ui\\../source/img/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_for_back_main_page.setIcon(icon)
        self.btn_for_back_main_page.setObjectName("btn_for_back_main_page")
        self.horizontalLayout.addWidget(self.btn_for_back_main_page)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.window_title = QtWidgets.QLabel(self.top_bar_widget)
        font = QtGui.QFont()
        font.setFamily("Plus Jakarta Sans ExtraBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.window_title.setFont(font)
        self.window_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.window_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: rgba(0, 0, 0, 0);")
        self.window_title.setObjectName("window_title")
        self.horizontalLayout.addWidget(self.window_title)
        self.verticalLayout.addWidget(self.top_bar_widget)
        self.workspace = QtWidgets.QStackedWidget(self.centralwidget)
        self.workspace.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.workspace.setStyleSheet("background: rgb(7, 11, 20);")
        self.workspace.setObjectName("workspace")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.workspace.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.workspace.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.workspace)
        main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.btn_for_back_main_page.setText(_translate("main_window", " Inicio"))
        self.window_title.setText(_translate("main_window", "Página Principal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
